sylius_resource:
    resources:
        bitbag_sylius_bonus_points.bonus_points_strategy:
            driver: doctrine/orm
            classes:
                model: Titi60\SyliusBonusPointsPlugin\Entity\BonusPointsStrategy
                interface: Titi60\SyliusBonusPointsPlugin\Entity\BonusPointsStrategyInterface
                form: Titi60\SyliusBonusPointsPlugin\Form\Type\BonusPointsStrategyType
                repository: Titi60\SyliusBonusPointsPlugin\Repository\BonusPointsStrategyRepository
