sylius_resource:
    resources:
        bitbag_sylius_bonus_points.bonus_points_strategy_rule:
            driver: doctrine/orm
            classes:
                model: Titi60\SyliusBonusPointsPlugin\Entity\BonusPointsStrategyRule
                interface: Titi60\SyliusBonusPointsPlugin\Entity\BonusPointsStrategyRuleInterface
