sylius_resource:
    resources:
        bitbag_sylius_bonus_points.bonus_points:
            driver: doctrine/orm
            classes:
                model: Titi60\SyliusBonusPointsPlugin\Entity\BonusPoints
                interface: Titi60\SyliusBonusPointsPlugin\Entity\BonusPointsInterface
                repository: Titi60\SyliusBonusPointsPlugin\Repository\BonusPointsRepository
