sylius_resource:
    resources:
        bitbag_sylius_bonus_points.customer_bonus_points:
            driver: doctrine/orm
            classes:
                model: Titi60\SyliusBonusPointsPlugin\Entity\CustomerBonusPoints
                interface: Titi60\SyliusBonusPointsPlugin\Entity\CustomerBonusPointsInterface
